### ISSUE TITLE
The backgroundColor parameter of NavigationPaneThemeData.standard() does not take effect

### ISSUE THREAD

**Issue by Zhangxxl** [bdlukaa/fluent_ui#1008]
**Describe the bug**

The backgroundColor parameter of NavigationPaneThemeData.standard() does not take effect

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by bdlukaa** [comment]
The above commit renamed `NavigationPaneThemeData.standard` to `NavigationPaneThemeData.fromResources`, and removes the `backgroundColor` and `inactiveColor`, since they are not used anymore.

To change the backgroundColor or inactive color of the app, provide a new `NavigationPaneThemeData` on the `FluentThemeData`.
