### ISSUE TITLE
What is the purpose of the generated_plugin_registrant.dart file in the example/lib path and how it was generated

### ISSUE THREAD

**Issue by ZhongGuanbin** [bdlukaa/fluent_ui#1072]
When I was looking at the code for the example project, there was an automatically generated generated_plugin_registrant.dart file in the example/lib path, but I couldn't find a reference to it. What is the purpose of this file and how it was generated. The submission record of this file is shown in the following figure

![image](https://github.com/bdlukaa/fluent_ui/assets/93035140/dde5b7e6-1e12-43a8-a042-c790713f213e)

**Comment by ZhongGuanbin** [comment]
When I entered the Flutter build web command, a description of "generated_plugin-registration. dart found. deleted" appeared on the command line, and then the generated_plugin-registration. dart file in the example/lib path was deleted. So why is this? What actions have been completed in this process? Is the generated plugin register. dart file a necessary file for compiling web applications? The command line information when compiling web applications is as follows. Thank you very much for your help
![image](https://github.com/bdlukaa/fluent_ui/assets/93035140/24080e5c-c0d5-4b6d-bdf3-e682a910a2e9)

**Comment by WinXaito** [comment]
So, these files are effectively autogenerated by flutter. And they are in the example app (so not directly linked to `fluent_ui` library).

These files are generated by flutter at the compilation time.

We can see the same kind of file in the windows directory: https://github.com/bdlukaa/fluent_ui/blob/master/example/windows/flutter/generated_plugin_registrant.cc

-----

However, I'm not sure why I included this in that PR, probably a mistake. These file are definitly not problematic, but we could also add removed them and add them in the `.gitignore` file because they are generated by flutter at compilation.

**Comment by ZhongGuanbin** [comment]
> So, these files are effectively autogenerated by flutter. And they are in the example app (so not directly linked to `fluent_ui` library).
> 
> These files are generated by flutter at the compilation time.
> 
> We can see the same kind of file in the windows directory: https://github.com/bdlukaa/fluent_ui/blob/master/example/windows/flutter/generated_plugin_registrant.cc
> 
> However, I'm not sure why I included this in that PR, probably a mistake. These file are definitly not problematic, but we could also remove them and add them in the `.gitignore` file because they are generated by flutter at compilation.

Thank you very much for your reply. I raised this question because I couldn't find any references from him and couldn't reproduce this file. This may be a problem that occurred during the development of Flutter. If it does not affect its use, I will temporarily close this issue. Welcome everyone to find the answer to this phenomenon. Thank you again for your reply!
