### ISSUE TITLE
🐛 Multiple regressions on v3.6.0

### ISSUE THREAD

**Issue by WinXaito** [bdlukaa/fluent_ui#122]
Since 3.6.0, visible on Web demo:

## Buttons

- [x] IconButton: incorrect size or padding

![image](https://user-images.githubusercontent.com/8223773/147422749-c19fcb2b-f089-4650-aed7-74191198dea8.png)

- [x] TextButton / FilledButton / Outlined button: No more hover or pressed effect

- [x] TextButton has a blur effect

![image](https://user-images.githubusercontent.com/8223773/147422835-4d5a66ae-4e71-4799-bcac-70587773c61e.png)

- [x] FilledButton style is certainly not correct (According to Fluent documentation, I think  there is rounded corner and white foreground)

![image](https://user-images.githubusercontent.com/8223773/147422862-9f9d2a35-2e89-47d5-ba2f-a30344447980.png)

## TabView

- [x] Tabs doesn't have minimal size, so that produce the following things...

![image](https://user-images.githubusercontent.com/8223773/147422683-9d07dcea-cbf3-442d-b136-daed9bd4da99.png)

We don't have any more the *navigation* buttons.

- [x] Missing padding before close button

![image](https://user-images.githubusercontent.com/8223773/147422735-1df3c42f-7371-4b71-a3f0-032e64d5b16d.png)

## TreeView

- [x] Padding/margin seems very big to me ?

![image](https://user-images.githubusercontent.com/8223773/147422795-1b9321ab-7e51-4a40-a61b-00741056ece3.png)

**Comment by henry2man** [comment]
>  Missing padding before close button

@WinXaito You should put an `Spacer()` or something similar because the `tabWidthBehavior: TabWidthBehavior.equal,` config doesn't separate the tab label & close button (in this picture you'll see how close button is not right aligned): 
<img width="510" alt="Captura de pantalla 2021-12-27 a las 18 07 40" src="https://user-images.githubusercontent.com/4610108/147493037-43435eb5-5b5d-4936-b26d-7449d5b18a95.png">
