### ISSUE TITLE
System Brightness does not work in FluentApp on Windows

### ISSUE THREAD

**Issue by RemcoSchrijver** [bdlukaa/fluent_ui#194]
The defined system brightness does not function when on used on Windows in combination with a FluentApp.

The following line does not work:
https://github.com/bdlukaa/fluent_ui/blob/3975a774f0bf21d0f6ca4b6b63f181f78551e9eb/lib/src/app.dart#L390

Workaround right now is:
`
FluentApp(
  theme: ThemeData(
    brightness: MediaQueryData.fromWindow(WidgetsBinding.instance!.window).platformBrightness,
  )
)
`

Not entirely sure if there is a better way to do this?

**Comment by WinXaito** [comment]
> The following line does not work:

In fact, yes that's work. That's only doesn't work on root context. Do this for confirm that:

```dart
builder: (context, _) {
    print(MediaQuery.platformBrightnessOf(context));
    return Text('text')
},
```

`flutter: Brightness.dark`

---------------

Your theme is not correct, because you need to create a themeData for dark and light theme.

Add this for resolve your problem:

```dart
return FluentApp(
  themeMode: ThemeMode.system,
  theme: ThemeData(
    brightness: Brightness.light,
  ),
  darkTheme: ThemeData(
    brightness: Brightness.dark,
  ),
  ...
);
```

----

Please reopen this issue if that doesn't solve your problem.
