### ISSUE TITLE
After upgrading to Flutter 3.0 I can't run applications with fluent_ui🐛 

### ISSUE THREAD

**Issue by andrelrf1** [bdlukaa/fluent_ui#327]
**Describe the bug**
After the last Flutter update I could no longer run applications with fluent_ui for testing and not even in release mode.

**To Reproduce**
1. Upgrade to Flutter 3.0;
2. Run a project that has fluent_ui;
3. The error will appear in the terminal

**Expected behavior**
I expected the application to start correctly.

**Screenshots**
![image](https://user-images.githubusercontent.com/42091869/168088378-4a36c538-cdf9-4c70-87f5-f630c5a2dd89.png)

**Additional context**
- I'm using Flutter 3.0;
- I'm using Windows 11 on the latest public build.

**Comment by jtdLab** [comment]
Same problem here

**Comment by Dancovich** [comment]
The issue seems to be on `selection_controls.dart`.

On line 19 the method `buildToolbar` is overriden from `TextSelectionControls`, but the super method changed signature and now receives a `ClipboardStatusNotifier?` instead of a `ClipboardStatusNotifier`.

The error message also has a bunch of warnings about calling `WidgetsBinding.instance!.[something]`. `WidgetsBinding.instance` no longer returns `WidgetsBinding?` so the ! operator is unnecessary. I don't believe this has anything to do with the error though, it's just a warning.

Maybe other errors will appear once this is fixed. Right now fluent_ui seems to not be compatible with Flutter 3.0.
