### ISSUE TITLE
Use official `fluentui_system_icons` package 

### ISSUE THREAD

**Issue by henry2man** [bdlukaa/fluent_ui#376]
**Is your feature request related to a problem? Please describe.**
Given that Microsoft is publishing an specific package `fluentui_system_icons` (https://pub.dev/packages/fluentui_system_icons), we should:

- Deprecate or potentially remove our FluentIcons class
- Add new dependency 
- Update the example to use the official package. For now we will loose the search feature, but I'm going to notify MSFT team with our solution via generator in https://github.com/microsoft/fluentui-system-icons/issues/377

**Describe the solution you'd like**
Use the official FluentIcons package. 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by bdlukaa** [comment]
We used to use that iconset from microsoft before (https://pub.dev/packages/fluent_ui/changelog#004---22022021), but a lot of icons are missing and it doesn't look native. Using the fonts provided by microsoft itself is better, imo.

One thing that I've experimented is, if already in the Windows platform, we don't need to export the windows asset because the fluent ui icon set font is already installed in the system. You can find the icon list [here](https://docs.microsoft.com/en-us/windows/apps/design/style/segoe-ui-symbol-font#pua-e700-e900). FontFamily name is `Segoe MDL2 Assets`

More info:
- https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.fonticon?view=winrt-22621#examples

**Comment by WinXaito** [comment]
After, the microsoft icon library has certainly evolved in the last months...

(And according to what you said above, it was not the official microsoft lib that you used?)

**Comment by bdlukaa** [comment]
>  it was not the official microsoft lib that you used?

it was the same icon set
