### ISSUE TITLE
make PaneItem.body is not required and make the pane and the content can be exist on one time

### ISSUE THREAD

**Issue by frg2089** [bdlukaa/fluent_ui#548]
Hi.

I have a code like this
```dart
NavigationView(
  // ...
  pane: NavigationPane(
    selected: index,
    onChanged: _changedPage,
    items: [
      PaneItem(icon, title),
      PaneItem(icon, title),
      PaneItem(icon, title),
      if (_special) ...[
        PaneItemSeparator(),
        PaneItem(icon, title)
      ],
    ],
  ),
  content: Navigator(),
);
```

I can used `onChanged` event to push a page into `Navigator` at old version. (4.0.0-pre.4)

However, I cannot use it on latest version. (4.0.0 or higher)
Because at the latest version, the `pane` and the `content` cannot be exist on one time.

could you can make `PaneItem.body` is not required and make the `pane` and the `content` can be exist on one time?

Thanks.

**Comment by klondikedragon** [comment]
The new behavior that makes `PaneItem.body` required also makes the way I'm using `NavigationPane` more difficult as well, where the child that is passed in comes from the parent width (vRouter with TabbedNester routes): https://github.com/bdlukaa/fluent_ui/issues/226#issuecomment-1070267070

In this router approach, the child widget for each page are specified alongside the routes, and when there are nested tabbed routes, the child for a given pane item can be dynamic based on a specific tabbed sub-route, so it's not obvious how to convert to the new style.

For a simple application, `PaneItem.body` is certainly more convenient, so it would be really helpful to support both modes. Perhaps `PaneItem.body` should still be required so that users of the simple case remember to do the right thing (easy enough to pass a `const SizedBox.shrink()` that would get ignored), but that if `content` is specified it will override any content that would have been built from the pane item body. I'll submit a PR shortly along this direction.

**Comment by klondikedragon** [comment]
It looks like a cleaner approach will be an optional builder that can customize the NavigationBody built from the currently selected pane item, which could choose to just ignore the pane item's body and return something else instead.
