### ISSUE TITLE
Built-in sliver widgets

### ISSUE THREAD

**Issue by tukiri** [bdlukaa/fluent_ui#612]
In fluent_ui,i can't find the SliverAppBar widget.
But,the SliverAppBar can achieve this :
![10edbf8a981fee13c8722cc2a3f8802e (1)](https://user-images.githubusercontent.com/117457369/202499104-92ab9be7-b9ad-4e6f-bb77-a59c3be93bc9.gif)
Can fluent_ui have any other way to achieve that?
Or is there any way to use flutter widget in fluent_ui?

**Comment by bdlukaa** [comment]
Since Slivers are not widely used in the desktop platforms, they were not implemented into this package. Still, you can use slivers because they're part of the `flutter/widgets` library. For material slivers, you may need to use named imports

* https://docs.flutter.dev/development/ui/advanced/slivers
* #150

**Comment by tukiri** [comment]
> 由于 Slivers 在桌面平台中没有广泛使用，因此它们没有实现到这个包中。不过，您可以使用薄片，因为它们是库的一部分。对于材质薄片，可能需要使用命名导入`flutter/widgets`
> 
> * https://docs.flutter.dev/development/ui/advanced/slivers
> * [Fluent UI 与 Flutter Material 不兼容#150](https://github.com/bdlukaa/fluent_ui/issues/150)

thank you,i success make it good work!
