### ISSUE TITLE
use FluentTheme widget for MaterialApp

### ISSUE THREAD

**Issue by hugetiny** [bdlukaa/fluent_ui#711]
**Describe the bug**
I just want to use treeView in my material UI ,but get the exception below.

**To Reproduce**
The exception text indicates that 'Expanded' is one of the ancestors 
I did use TreeView inside the Expanded ,but still got the exception
```
@override
  Widget build(BuildContext context) {
    final themeData = Theme.of(context);
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        const Padding(padding: EdgeInsets.only(top: 10)),
        Text('create.selectFile'.tr,
            style: TextStyle(color: themeData.hintColor)),
        Expanded(
          child:TreeView(
            // key: treeViewKey,
            selectionMode: TreeViewSelectionMode.multiple,
            items: items,
          )
        ),
      ],
    );
  }
```
```
A FluentTheme widget is necessary to draw this layout.
To introduce a FluentTheme widget, you can either directly include one, or use a widget that contains FluentTheme itself, such as FluentApp
The specific widget that could not find a FluentTheme ancestor was:
  TreeView
The ancestors of this widget were:
  Expanded
  Column
  FileListView
  Expanded
  Column
  _FormScope
  WillPopScope
  Form-[LabeledGlobalKey<FormState>#b2587]
  SizedBox
  Builder
  Semantics
  DefaultTextStyle
...
```

**Expected behavior**
treeview works well in material UI

**Comment by h3x4d3c1m4l** [comment]
Fluent widgets need a source for their theme data. You can either use `FluentApp` (instead of `WidgetsApp`, `CupertinoApp` or `MaterialApp`) as your (close to) root widget, or include a `FluentTheme` widget.

It might just work when you wrap your `TreeView` with `FluentTheme` widget.

**Comment by hugetiny** [comment]
> Fluent widgets need a source for their theme data. You can either use `FluentApp` (instead of `WidgetsApp`, `CupertinoApp` or `MaterialApp`) as your (close to) root widget, or include a `FluentTheme` widget.
> 
> It might just work when you wrap your `TreeView` with `FluentTheme` widget.

I tried wraping TreeView in a FluentTheme widget
```
import 'package:fluent_ui/fluent_ui.dart' hide Page;
...
      FluentTheme(
          data: FluentTheme.of(context),
          child:TreeView(
...
```
The exception:
```
Null check operator used on a null value
```
But I can't find what is missed

**Comment by h3x4d3c1m4l** [comment]
Ah I see! So this `FluentTheme.of(context)` line will try to find an existing `FluentTheme` instance which does not exist yet.

Try to replace that by a new instance of `FleuntTheme`.

**Comment by hugetiny** [comment]
> Ah I see! So this `FluentTheme.of(context)` line will try to find an existing `FluentTheme` instance in your widget tree but it does not exist yet. That is why it crashes.
> 
> Try to replace that by a new instance of `ThemeData`.

Since Fluent UI is a wrap for Material UI ,ThemeData should extend the Material UI's theme data.
I hope so...

**Comment by h3x4d3c1m4l** [comment]
Microsoft Fluent UI is not an extension of Material UI. As such `fluent_ui` is also not an extension or wrapper of `material`. Unfortunately, because of that, the `material` styling system is not usable for `fluent_ui` at all (imo doing theming that way would be very confusing for users). As such it brings it's own theming system. Just like the Cupertino components are also not an extension of the Material components.

`fluent_ui` definitely uses some `material` component because sometimes that's the better option than to "reinvent the wheel". But it definitely tries to minimize dependency on the `material` library.

Could you try something like this to fix the issue?
<img width="343" alt="image" src="https://user-images.githubusercontent.com/2611894/215992600-a9b08402-f04a-4ffe-aa99-4c654eae335c.png">

**Comment by hugetiny** [comment]
@h3x4d3c1m4l thank you,it works

**Comment by h3x4d3c1m4l** [comment]
Glad to hear. Thanks for letting us know!
