### ISSUE TITLE
TextFormBox's initialValue is missing in fluent_ui version 4.4.0!

### ISSUE THREAD

**Issue by AriDevC** [bdlukaa/fluent_ui#749]
Hello, I wonder if the removal of _initialValue_ property of _TextFormBox_ was intentional or accidental in _fluent_ui version 4.4.0._

My use case for it, is that I sometimes don't need a controller for a textfield, but do need to set an initial value to it. So it's very helpful and useful if this property is brought back.

Same goes to the _header_ property, it's also been removed!

It would be helpful if they are brought back in the next version.

Thanks in advance.

**Comment by bdlukaa** [comment]
Hello! They were intentionally removed. See the [changelog](https://github.com/bdlukaa/fluent_ui/blob/master/CHANGELOG.md)

The `initialValue` was removed because it was also removed from the flutter framework as well (`TextField` and `CupertinoTextField`);
For the header, you can use wrap your field in an `InfoLabel` widget and provide it there.

**Comment by Ahmed-gubara** [comment]
I think it shouldn't be deleted.
TextFormBox is a Form inputs. just like
```
CupertinoTextFormFieldRow(initialValue: ,),
TextFormField(initialValue: ,)
```

https://github.com/flutter/flutter/blob/010e2c9cfc09a4f1506b9ad40f2f49aadf133c51/packages/flutter/lib/src/material/text_form_field.dart#L100
