### ISSUE TITLE
🐛 Buttons miss bottom border accent

### ISSUE THREAD

**Issue by robkri** [bdlukaa/fluent_ui#920]
Buttons use a uniformly colored border. But the bottom border should be darker:

![Button_Borders](https://github.com/bdlukaa/fluent_ui/assets/103884835/81d4e825-43de-4e21-941b-1aab1edeed3c)

Except for the unfilled button in dark mode: It doesn't seem to have a darker bottom border but a lighter top border.

**Comment by bdlukaa** [comment]
The native button border³ is like following:

* https://github.com/microsoft/microsoft-ui-xaml/blob/main/dev/CommonStyles/Button_themeresources.xaml#L33
* https://github.com/microsoft/microsoft-ui-xaml/blob/main/dev/CommonStyles/Button_themeresources.xaml#L18
* https://github.com/microsoft/microsoft-ui-xaml/blob/4b77c2489f40261d3f7a6718d67760c3747d4600/dev/CommonStyles/Common_themeresources_any.xaml#L239-L244

The current button border is like the following:
* https://github.com/bdlukaa/fluent_ui/blob/master/lib/src/controls/inputs/buttons/button.dart#L45-L47

I'm not sure on how to replicate the native border - since it's represented as a linear gradient brush. ¹ Is it a mix between both colors? ² Is it a linear gradient? ³ Is it secondary at the top and default at bottom?

---

* https://github.com/microsoft/microsoft-ui-xaml/blob/main/dev/CommonStyles/Button_themeresources.xaml#L140-L141
* https://learn.microsoft.com/en-us/uwp/api/windows.ui.xaml.media.brush?view=winrt-22621
* https://learn.microsoft.com/en-us/uwp/api/windows.ui.xaml.media.lineargradientbrush?view=winrt-22621

> The [StartPoint](https://learn.microsoft.com/en-us/uwp/api/windows.ui.xaml.media.lineargradientbrush.startpoint?view=winrt-22621#windows-ui-xaml-media-lineargradientbrush-startpoint) and [EndPoint](https://learn.microsoft.com/en-us/uwp/api/windows.ui.xaml.media.lineargradientbrush.endpoint?view=winrt-22621#windows-ui-xaml-media-lineargradientbrush-endpoint) properties of LinearGradientBrush describe two points in a relative coordinate space. This creates an orientation for the gradient, and typically this specifies a horizontal gradient, or a vertical gradient.

As per the documentation, it seems like ³ is the correct question. If so, I'm not sure on how to do it in flutter since it doesn't support complex borders with `borderRadius` specified. 

---

With that said, I think this issue can be mitigated by properly applying the correct colors and border width, but I don't think this can be solved.

**Comment by Ferry-200** [comment]
The native border is a linear gradient. The colors are (255, 255, 255, 0.08) and (0, 0, 0, 0.40). The stops may be 0.90 and 1.0.
Maybe extends `BoxBorder` and override the `Paint` method can paint the gradient border.

**Comment by Ferry-200** [comment]
Extends `BoxBorder` in painting and override the `Paint` method .Create a `Paint` and set the shader property with `gradient.createShader`. Pass it to `canva.draw` method. Just imitate what `Border` does.
But I am not familiar with your project structure, I am not sure it will help.
