### ISSUE TITLE
[Feature Request] Implement Color Picker

### ISSUE THREAD

**Issue by zhangweidi** [bdlukaa/fluent_ui#963]
I only found color pickers that depended on material, I hope it doesn't depend on material at all. Is there a color picker that can meet this requirement?

Thank you!

**Comment by bdlukaa** [comment]
Hello! Windows UI has guidelines for a [Color Picker control](https://learn.microsoft.com/en-us/windows/apps/design/controls/color-picker), but it is substantially complex to make an implementation for it. Since it is not a core component, I decided to not implement it, but PRs are more than welcome - so feel free to make a pull request.

The existent flutter color picker packages out there just use material as a base, since it doesn't provide specific guidelines for a color picker. Also note that we like to keep `fluent_ui` dependencies minimum and only add any only when necessary, which means the picker implementation would need to be done from scratch.

**Additional resources**
* https://learn.microsoft.com/en-us/windows/apps/design/controls/color-picker
